# Config file for automatic testing at travis-ci.org

language: python

# Use container based infrastructure
sudo: false

env:
  - CMD=./test

python:
  - 2.7
  - 2.6
  - 3.4
  - 3.3

matrix:
  # allow_failures:
  #   - env: CMD="flake8 aldryn_categories"
  fast_finish: true
  include:
    - env: CMD="flake8 aldryn_categories"

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip wheel --wheel-dir $HOME/.wheelhouse -r test_requirements.txt
  - pip install --use-wheel --no-index --find-links=$HOME/.wheelhouse -r test_requirements.txt

script: $CMD

# TODO: Add coverage reporting
# after_success: coveralls
